/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        sans: ['"IBM Plex Sans"', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        mono: ['"IBM Plex Mono"', 'ui-monospace', 'monospace'],
        serif: ['"Noto Serif JP"', 'ui-serif', 'serif'],
      },
      colors: {
        accent: '#C13D2B',
        'accent-ink': '#A8341F',
        'accent-wash': '#FBF1ED',
        'accent-wash-border': '#F0DDD4',
        'accent-wash-text': '#7A4A3D',
        canvas: '#F4F0E7',
        'canvas-mobile': '#F1EAD9',
        'canvas-detail': '#FBF8F1',
        sidebar: '#EFE9DB',
        surface: '#FFFFFF',
        'surface-sheet': '#FAF6EE',
        'surface-sunken': '#F6F2E8',
        'folder-tile': '#F4ECDC',
        'row-hover': '#FBF8F1',
        'chip-bg': '#F1ECE0',
        'chip-bg-alt': '#E5DCC9',
        'pill-idle': '#EAE1CE',
        'pill-idle-text': '#6F675B',
        ink: '#2B2722',
        'ink-title': '#26221D',
        'ink-2': '#5E5648',
        'ink-3': '#A79E8E',
        'ink-mono': '#9A917E',
        'ink-mono-faint': '#B0A68F',
        'icon-default': '#B6AB94',
        hairline: '#E6DECE',
        'hairline-card': '#E9E1D1',
        'hairline-warm': '#E2D9C6',
        'hairline-faint': '#EDE7DA',
        'sync-green': '#5B9A6B',
        chevron: '#C9BFA9',
        dk: {
          bg: '#1E1B17',
          card: '#28241E',
          sidebar: '#231F1B',
          'row-hover': '#2D2922',
          'surface-sunken': '#191613',
          border: '#38322A',
          divider: '#332E27',
          ink: '#F0E9DB',
          'ink-2': '#B8AE9C',
          'ink-3': '#8A8173',
          'ink-faint': '#7E7460',
          accent: '#E2705A',
          'accent-wash': '#2B1D1A',
          'accent-wash-border': '#3C2520',
          'chip-bg': '#322E26',
          'chip-border': '#3C362D',
          'pill-idle': '#2E2A23',
          'pill-text': '#B8AE9C',
          green: '#6FB07E',
        },
      },
    },
  },
  plugins: [],
}
